### ISSUE TITLE
Error when calling `.artillery()` in sample

### ISSUE THREAD

**Issue by mattemoore** [EasyGraphQL/easygraphql-load-tester#83]
index.js

```
'use strict' 

const { GraphQLSchema, GraphQLObjectType, GraphQLString } = require('graphql')
const EasyGraphQLLoadTester = require('easygraphql-load-tester')

const schema = new GraphQLSchema({
  query: new GraphQLObjectType({
    name: 'RootQueryType',
    fields: {
      hello: {
        type: GraphQLString,
        resolve() {
          return 'world';
        }
      }
    }
  })
});

const loadTester = new EasyGraphQLLoadTester(schema)
const testCases = loadTester.artillery()

module.exports = {
  testCases
}
```

artillery.yml
```
config:
    target: "http://localhost:5000/"
    phases:
      - duration: 5
        arrivalRate: 1
    processor: "./index.js"
  scenarios:
    - name: "GraphQL Query load test"
      flow:
        - function: "testCases"
        - loop:
            - post:
                url: "/"
                json:
                  query: "{{ $loopElement.query }}"
            - log: "----------------------------------"
            - log: "Sent a request to the Query: {{ $loopElement.name }}"
          over: cases
```

package.json
```
  "scripts": {
    "artillery": "artillery run artillery.yml"
  },
```

Error message:
```
matt-devbox@mattdevbox-VirtualBox:~/Code/server-monitoring/load$ npm run artillery

> load@1.0.0 artillery /home/matt-devbox/Code/server-monitoring/load
> artillery run artillery.yml

.   /home/matt-devbox/Code/server-monitoring/load/node_modules/easygraphql-load-tester/lib/index.js:145
                _this.schema[schemaDefinition.definition].fields.forEach(function (query) {
                                                          ^

TypeError: Cannot read property 'fields' of undefined
    at /home/matt-devbox/Code/server-monitoring/load/node_modules/easygraphql-load-tester/lib/index.js:145:59
    at Array.forEach (<anonymous>)
    at LoadTesting.module.exports.LoadTesting.createQueries (/home/matt-devbox/Code/server-monitoring/load/node_modules/easygraphql-load-tester/lib/index.js:144:31)
    at LoadTesting.module.exports.LoadTesting.artillery (/home/matt-devbox/Code/server-monitoring/load/node_modules/easygraphql-load-tester/lib/index.js:35:28)
    at Object.<anonymous> (/home/matt-devbox/Code/server-monitoring/load/index.js:21:30)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
```
